//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.ysolutions.converter.models.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ф0409303_QNAME = new QName("urn:cbr-ru:rep0409303:v4.0.4.5", "\u04240409303");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.ysolutions.converter.models.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ф0409303 }
     * 
     */
    public Ф0409303 createФ0409303() {
        return new Ф0409303();
    }

    /**
     * Create an instance of {@link Ф0409303Составитель }
     * 
     */
    public Ф0409303Составитель createФ0409303Составитель() {
        return new Ф0409303Составитель();
    }

    /**
     * Create an instance of {@link Ф0409303СоставительРуководитель }
     * 
     */
    public Ф0409303СоставительРуководитель createФ0409303СоставительРуководитель() {
        return new Ф0409303СоставительРуководитель();
    }

    /**
     * Create an instance of {@link Ф0409303СоставительГлавБух }
     * 
     */
    public Ф0409303СоставительГлавБух createФ0409303СоставительГлавБух() {
        return new Ф0409303СоставительГлавБух();
    }

    /**
     * Create an instance of {@link Ф0409303СоставительИсполнитель }
     * 
     */
    public Ф0409303СоставительИсполнитель createФ0409303СоставительИсполнитель() {
        return new Ф0409303СоставительИсполнитель();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303 }
     * 
     */
    public Ф0409303Данные303 createФ0409303Данные303() {
        return new Ф0409303Данные303();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303Договор }
     * 
     */
    public Ф0409303Данные303Договор createФ0409303Данные303Договор() {
        return new Ф0409303Данные303Договор();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР1 }
     * 
     */
    public Ф0409303Данные303ДоговорР1 createФ0409303Данные303ДоговорР1() {
        return new Ф0409303Данные303ДоговорР1();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР2 }
     * 
     */
    public Ф0409303Данные303ДоговорР2 createФ0409303Данные303ДоговорР2() {
        return new Ф0409303Данные303ДоговорР2();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР3 }
     * 
     */
    public Ф0409303Данные303ДоговорР3 createФ0409303Данные303ДоговорР3() {
        return new Ф0409303Данные303ДоговорР3();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР5 }
     * 
     */
    public Ф0409303Данные303ДоговорР5 createФ0409303Данные303ДоговорР5() {
        return new Ф0409303Данные303ДоговорР5();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР6 }
     * 
     */
    public Ф0409303Данные303ДоговорР6 createФ0409303Данные303ДоговорР6() {
        return new Ф0409303Данные303ДоговорР6();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР7 }
     * 
     */
    public Ф0409303Данные303ДоговорР7 createФ0409303Данные303ДоговорР7() {
        return new Ф0409303Данные303ДоговорР7();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР8 }
     * 
     */
    public Ф0409303Данные303ДоговорР8 createФ0409303Данные303ДоговорР8() {
        return new Ф0409303Данные303ДоговорР8();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР9 }
     * 
     */
    public Ф0409303Данные303ДоговорР9 createФ0409303Данные303ДоговорР9() {
        return new Ф0409303Данные303ДоговорР9();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорУсл }
     * 
     */
    public Ф0409303Данные303ДоговорУсл createФ0409303Данные303ДоговорУсл() {
        return new Ф0409303Данные303ДоговорУсл();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорУслДогПоУсл }
     * 
     */
    public Ф0409303Данные303ДоговорУслДогПоУсл createФ0409303Данные303ДоговорУслДогПоУсл() {
        return new Ф0409303Данные303ДоговорУслДогПоУсл();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР4Обесп }
     * 
     */
    public Ф0409303Данные303ДоговорР4Обесп createФ0409303Данные303ДоговорР4Обесп() {
        return new Ф0409303Данные303ДоговорР4Обесп();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорНеА }
     * 
     */
    public Ф0409303Данные303ДоговорНеА createФ0409303Данные303ДоговорНеА() {
        return new Ф0409303Данные303ДоговорНеА();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорПогшн }
     * 
     */
    public Ф0409303Данные303ДоговорПогшн createФ0409303Данные303ДоговорПогшн() {
        return new Ф0409303Данные303ДоговорПогшн();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорИст }
     * 
     */
    public Ф0409303Данные303ДоговорИст createФ0409303Данные303ДоговорИст() {
        return new Ф0409303Данные303ДоговорИст();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорИстИстСум }
     * 
     */
    public Ф0409303Данные303ДоговорИстИстСум createФ0409303Данные303ДоговорИстИстСум() {
        return new Ф0409303Данные303ДоговорИстИстСум();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорИстИстДог }
     * 
     */
    public Ф0409303Данные303ДоговорИстИстДог createФ0409303Данные303ДоговорИстИстДог() {
        return new Ф0409303Данные303ДоговорИстИстДог();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР1ГВЗ }
     * 
     */
    public Ф0409303Данные303ДоговорР1ГВЗ createФ0409303Данные303ДоговорР1ГВЗ() {
        return new Ф0409303Данные303ДоговорР1ГВЗ();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР2Обрем }
     * 
     */
    public Ф0409303Данные303ДоговорР2Обрем createФ0409303Данные303ДоговорР2Обрем() {
        return new Ф0409303Данные303ДоговорР2Обрем();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорР10 }
     * 
     */
    public Ф0409303Данные303ДоговорР10 createФ0409303Данные303ДоговорР10() {
        return new Ф0409303Данные303ДоговорР10();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТранш }
     * 
     */
    public Ф0409303Данные303ДоговорТранш createФ0409303Данные303ДоговорТранш() {
        return new Ф0409303Данные303ДоговорТранш();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншР2Т }
     * 
     */
    public Ф0409303Данные303ДоговорТраншР2Т createФ0409303Данные303ДоговорТраншР2Т() {
        return new Ф0409303Данные303ДоговорТраншР2Т();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншР3Т }
     * 
     */
    public Ф0409303Данные303ДоговорТраншР3Т createФ0409303Данные303ДоговорТраншР3Т() {
        return new Ф0409303Данные303ДоговорТраншР3Т();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншР5Т }
     * 
     */
    public Ф0409303Данные303ДоговорТраншР5Т createФ0409303Данные303ДоговорТраншР5Т() {
        return new Ф0409303Данные303ДоговорТраншР5Т();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншР6Т }
     * 
     */
    public Ф0409303Данные303ДоговорТраншР6Т createФ0409303Данные303ДоговорТраншР6Т() {
        return new Ф0409303Данные303ДоговорТраншР6Т();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншР7Т }
     * 
     */
    public Ф0409303Данные303ДоговорТраншР7Т createФ0409303Данные303ДоговорТраншР7Т() {
        return new Ф0409303Данные303ДоговорТраншР7Т();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншР9Т }
     * 
     */
    public Ф0409303Данные303ДоговорТраншР9Т createФ0409303Данные303ДоговорТраншР9Т() {
        return new Ф0409303Данные303ДоговорТраншР9Т();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншУслТ }
     * 
     */
    public Ф0409303Данные303ДоговорТраншУслТ createФ0409303Данные303ДоговорТраншУслТ() {
        return new Ф0409303Данные303ДоговорТраншУслТ();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншУслТДогПоУсл }
     * 
     */
    public Ф0409303Данные303ДоговорТраншУслТДогПоУсл createФ0409303Данные303ДоговорТраншУслТДогПоУсл() {
        return new Ф0409303Данные303ДоговорТраншУслТДогПоУсл();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншР4ОбеспТ }
     * 
     */
    public Ф0409303Данные303ДоговорТраншР4ОбеспТ createФ0409303Данные303ДоговорТраншР4ОбеспТ() {
        return new Ф0409303Данные303ДоговорТраншР4ОбеспТ();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншНеАТ }
     * 
     */
    public Ф0409303Данные303ДоговорТраншНеАТ createФ0409303Данные303ДоговорТраншНеАТ() {
        return new Ф0409303Данные303ДоговорТраншНеАТ();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншПогшнТ }
     * 
     */
    public Ф0409303Данные303ДоговорТраншПогшнТ createФ0409303Данные303ДоговорТраншПогшнТ() {
        return new Ф0409303Данные303ДоговорТраншПогшнТ();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншИстТ }
     * 
     */
    public Ф0409303Данные303ДоговорТраншИстТ createФ0409303Данные303ДоговорТраншИстТ() {
        return new Ф0409303Данные303ДоговорТраншИстТ();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншИстТИстСум }
     * 
     */
    public Ф0409303Данные303ДоговорТраншИстТИстСум createФ0409303Данные303ДоговорТраншИстТИстСум() {
        return new Ф0409303Данные303ДоговорТраншИстТИстСум();
    }

    /**
     * Create an instance of {@link Ф0409303Данные303ДоговорТраншИстТИстДог }
     * 
     */
    public Ф0409303Данные303ДоговорТраншИстТИстДог createФ0409303Данные303ДоговорТраншИстТИстДог() {
        return new Ф0409303Данные303ДоговорТраншИстТИстДог();
    }

    /**
     * Create an instance of {@link Ф0409303НетДанных }
     * 
     */
    public Ф0409303НетДанных createФ0409303НетДанных() {
        return new Ф0409303НетДанных();
    }

    /**
     * Create an instance of {@link Ф0409303Пояснение }
     * 
     */
    public Ф0409303Пояснение createФ0409303Пояснение() {
        return new Ф0409303Пояснение();
    }

    /**
     * Create an instance of {@link Ф0409303ПротоколКонтроля }
     * 
     */
    public Ф0409303ПротоколКонтроля createФ0409303ПротоколКонтроля() {
        return new Ф0409303ПротоколКонтроля();
    }

    /**
     * Create an instance of {@link Ф0409303ПротоколКонтроляСообщение }
     * 
     */
    public Ф0409303ПротоколКонтроляСообщение createФ0409303ПротоколКонтроляСообщение() {
        return new Ф0409303ПротоколКонтроляСообщение();
    }

    /**
     * Create an instance of {@link Ф0409303ПояснениеОшибок }
     * 
     */
    public Ф0409303ПояснениеОшибок createФ0409303ПояснениеОшибок() {
        return new Ф0409303ПояснениеОшибок();
    }

    /**
     * Create an instance of {@link Ф0409303ПояснениеОшибокПояснениеКодОш }
     * 
     */
    public Ф0409303ПояснениеОшибокПояснениеКодОш createФ0409303ПояснениеОшибокПояснениеКодОш() {
        return new Ф0409303ПояснениеОшибокПояснениеКодОш();
    }

    /**
     * Create an instance of {@link Ф0409303ИнфПК }
     * 
     */
    public Ф0409303ИнфПК createФ0409303ИнфПК() {
        return new Ф0409303ИнфПК();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ф0409303 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Ф0409303 }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cbr-ru:rep0409303:v4.0.4.5", name = "\u04240409303")
    public JAXBElement<Ф0409303> createФ0409303(Ф0409303 value) {
        return new JAXBElement<Ф0409303>(_Ф0409303_QNAME, Ф0409303 .class, null, value);
    }

}
