//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:cbr-ru:rep0409303:v4.0.4.5", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.ysolutions.converter.models.xml;
