//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ВидОЭСтип.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ВидОЭСтип"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Отчетность КО"/&gt;
 *     &lt;enumeration value="Отчетность ТУ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "\u0412\u0438\u0434\u041e\u042d\u0421\u0442\u0438\u043f")
@XmlEnum
public enum ВидОЭСтип {

    @XmlEnumValue("\u041e\u0442\u0447\u0435\u0442\u043d\u043e\u0441\u0442\u044c \u041a\u041e")
    ОТЧЕТНОСТЬ_КО("\u041e\u0442\u0447\u0435\u0442\u043d\u043e\u0441\u0442\u044c \u041a\u041e"),
    @XmlEnumValue("\u041e\u0442\u0447\u0435\u0442\u043d\u043e\u0441\u0442\u044c \u0422\u0423")
    ОТЧЕТНОСТЬ_ТУ("\u041e\u0442\u0447\u0435\u0442\u043d\u043e\u0441\u0442\u044c \u0422\u0423");
    private final String value;

    ВидОЭСтип(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ВидОЭСтип fromValue(String v) {
        for (ВидОЭСтип c: ВидОЭСтип.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
