//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорР1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорР1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р1_1" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка255Непустая" /&gt;
 *       &lt;attribute name="Р1_2" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОГРНтип" /&gt;
 *       &lt;attribute name="Р1_3" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОГРН_ИП-лок" /&gt;
 *       &lt;attribute name="Р1_4" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р1_5" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаДо100Непустая-лок" /&gt;
 *       &lt;attribute name="Р1_5тип" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок"&gt;
 *             &lt;enumeration value="ИНН"/&gt;
 *             &lt;enumeration value="КИО"/&gt;
 *             &lt;enumeration value="TIN"/&gt;
 *             &lt;enumeration value="LEI"/&gt;
 *             &lt;enumeration value="SWIFT"/&gt;
 *             &lt;enumeration value="NUM"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Р1_6" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОКПОдо14ц-лок" /&gt;
 *       &lt;attribute name="Р1_7" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОКСМтип" /&gt;
 *       &lt;attribute name="Р1_8" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок" /&gt;
 *       &lt;attribute name="Р1_9" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка2" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u04201")
public class Ф0409303Данные303ДоговорР1 {

    @XmlAttribute(name = "\u04201_1", required = true)
    protected String р11;
    @XmlAttribute(name = "\u04201_2")
    protected String р12;
    @XmlAttribute(name = "\u04201_3")
    protected String р13;
    @XmlAttribute(name = "\u04201_4")
    protected XMLGregorianCalendar р14;
    @XmlAttribute(name = "\u04201_5", required = true)
    protected String р15;
    @XmlAttribute(name = "\u04201_5\u0442\u0438\u043f", required = true)
    protected String р15Тип;
    @XmlAttribute(name = "\u04201_6")
    protected String р16;
    @XmlAttribute(name = "\u04201_7", required = true)
    protected String р17;
    @XmlAttribute(name = "\u04201_8")
    protected String р18;
    @XmlAttribute(name = "\u04201_9")
    protected String р19;

    /**
     * Gets the value of the р11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР11() {
        return р11;
    }

    /**
     * Sets the value of the р11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР11(String value) {
        this.р11 = value;
    }

    /**
     * Gets the value of the р12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР12() {
        return р12;
    }

    /**
     * Sets the value of the р12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР12(String value) {
        this.р12 = value;
    }

    /**
     * Gets the value of the р13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР13() {
        return р13;
    }

    /**
     * Sets the value of the р13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР13(String value) {
        this.р13 = value;
    }

    /**
     * Gets the value of the р14 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР14() {
        return р14;
    }

    /**
     * Sets the value of the р14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР14(XMLGregorianCalendar value) {
        this.р14 = value;
    }

    /**
     * Gets the value of the р15 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР15() {
        return р15;
    }

    /**
     * Sets the value of the р15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР15(String value) {
        this.р15 = value;
    }

    /**
     * Gets the value of the р15Тип property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР15Тип() {
        return р15Тип;
    }

    /**
     * Sets the value of the р15Тип property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР15Тип(String value) {
        this.р15Тип = value;
    }

    /**
     * Gets the value of the р16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР16() {
        return р16;
    }

    /**
     * Sets the value of the р16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР16(String value) {
        this.р16 = value;
    }

    /**
     * Gets the value of the р17 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР17() {
        return р17;
    }

    /**
     * Sets the value of the р17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР17(String value) {
        this.р17 = value;
    }

    /**
     * Gets the value of the р18 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР18() {
        return р18;
    }

    /**
     * Sets the value of the р18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР18(String value) {
        this.р18 = value;
    }

    /**
     * Gets the value of the р19 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР19() {
        return р19;
    }

    /**
     * Sets the value of the р19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР19(String value) {
        this.р19 = value;
    }

}
