//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорТраншР3т complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорТраншР3т"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р3_2" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка255Непустая" /&gt;
 *       &lt;attribute name="Р3_3" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р3_4" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р3_5" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка3с-лок" /&gt;
 *       &lt;attribute name="Р3_6" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка3с-лок" /&gt;
 *       &lt;attribute name="Р3_7" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р3_8" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р3_9" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка255Непустая" /&gt;
 *       &lt;attribute name="Р3_10" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят3.3диапазон-лок" /&gt;
 *       &lt;attribute name="Р3_11" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят3.3диапазон-лок" /&gt;
 *       &lt;attribute name="Р3_12" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят3.3диапазон-лок" /&gt;
 *       &lt;attribute name="Р3_13н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Целое5неотриц-лок" /&gt;
 *       &lt;attribute name="Р3_14" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаДо4000Непустая-лок" /&gt;
 *       &lt;attribute name="Р3_17" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка255Непустая" /&gt;
 *       &lt;attribute name="Р3_18" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаДо4000Непустая-лок" /&gt;
 *       &lt;attribute name="Р3_19" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят3.3неотриц-лок" /&gt;
 *       &lt;attribute name="Р3_20" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят3.3неотриц-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u0422\u0440\u0430\u043d\u0448\u04203\u0442")
public class Ф0409303Данные303ДоговорТраншР3Т {

    @XmlAttribute(name = "\u04203_2")
    protected String р32;
    @XmlAttribute(name = "\u04203_3")
    protected BigDecimal р33;
    @XmlAttribute(name = "\u04203_4")
    protected BigDecimal р34;
    @XmlAttribute(name = "\u04203_5")
    protected String р35;
    @XmlAttribute(name = "\u04203_6")
    protected String р36;
    @XmlAttribute(name = "\u04203_7")
    protected XMLGregorianCalendar р37;
    @XmlAttribute(name = "\u04203_8")
    protected XMLGregorianCalendar р38;
    @XmlAttribute(name = "\u04203_9")
    protected String р39;
    @XmlAttribute(name = "\u04203_10")
    protected BigDecimal р310;
    @XmlAttribute(name = "\u04203_11")
    protected BigDecimal р311;
    @XmlAttribute(name = "\u04203_12")
    protected BigDecimal р312;
    @XmlAttribute(name = "\u04203_13\u043d")
    protected BigInteger р313Н;
    @XmlAttribute(name = "\u04203_14")
    protected String р314;
    @XmlAttribute(name = "\u04203_17")
    protected String р317;
    @XmlAttribute(name = "\u04203_18")
    protected String р318;
    @XmlAttribute(name = "\u04203_19")
    protected BigDecimal р319;
    @XmlAttribute(name = "\u04203_20")
    protected BigDecimal р320;

    /**
     * Gets the value of the р32 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР32() {
        return р32;
    }

    /**
     * Sets the value of the р32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР32(String value) {
        this.р32 = value;
    }

    /**
     * Gets the value of the р33 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР33() {
        return р33;
    }

    /**
     * Sets the value of the р33 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР33(BigDecimal value) {
        this.р33 = value;
    }

    /**
     * Gets the value of the р34 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР34() {
        return р34;
    }

    /**
     * Sets the value of the р34 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР34(BigDecimal value) {
        this.р34 = value;
    }

    /**
     * Gets the value of the р35 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР35() {
        return р35;
    }

    /**
     * Sets the value of the р35 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР35(String value) {
        this.р35 = value;
    }

    /**
     * Gets the value of the р36 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР36() {
        return р36;
    }

    /**
     * Sets the value of the р36 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР36(String value) {
        this.р36 = value;
    }

    /**
     * Gets the value of the р37 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР37() {
        return р37;
    }

    /**
     * Sets the value of the р37 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР37(XMLGregorianCalendar value) {
        this.р37 = value;
    }

    /**
     * Gets the value of the р38 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР38() {
        return р38;
    }

    /**
     * Sets the value of the р38 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР38(XMLGregorianCalendar value) {
        this.р38 = value;
    }

    /**
     * Gets the value of the р39 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР39() {
        return р39;
    }

    /**
     * Sets the value of the р39 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР39(String value) {
        this.р39 = value;
    }

    /**
     * Gets the value of the р310 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР310() {
        return р310;
    }

    /**
     * Sets the value of the р310 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР310(BigDecimal value) {
        this.р310 = value;
    }

    /**
     * Gets the value of the р311 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР311() {
        return р311;
    }

    /**
     * Sets the value of the р311 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР311(BigDecimal value) {
        this.р311 = value;
    }

    /**
     * Gets the value of the р312 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР312() {
        return р312;
    }

    /**
     * Sets the value of the р312 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР312(BigDecimal value) {
        this.р312 = value;
    }

    /**
     * Gets the value of the р313Н property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getР313Н() {
        return р313Н;
    }

    /**
     * Sets the value of the р313Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setР313Н(BigInteger value) {
        this.р313Н = value;
    }

    /**
     * Gets the value of the р314 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР314() {
        return р314;
    }

    /**
     * Sets the value of the р314 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР314(String value) {
        this.р314 = value;
    }

    /**
     * Gets the value of the р317 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР317() {
        return р317;
    }

    /**
     * Sets the value of the р317 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР317(String value) {
        this.р317 = value;
    }

    /**
     * Gets the value of the р318 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР318() {
        return р318;
    }

    /**
     * Sets the value of the р318 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР318(String value) {
        this.р318 = value;
    }

    /**
     * Gets the value of the р319 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР319() {
        return р319;
    }

    /**
     * Sets the value of the р319 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР319(BigDecimal value) {
        this.р319 = value;
    }

    /**
     * Gets the value of the р320 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР320() {
        return р320;
    }

    /**
     * Sets the value of the р320 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР320(BigDecimal value) {
        this.р320 = value;
    }

}
