//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303ПояснениеОшибок complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303ПояснениеОшибок"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ПояснениеКодОш" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303ПояснениеОшибокПояснениеКодОш" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u041f\u043e\u044f\u0441\u043d\u0435\u043d\u0438\u0435\u041e\u0448\u0438\u0431\u043e\u043a", propOrder = {
    "\u043f\u043e\u044f\u0441\u043d\u0435\u043d\u0438\u0435\u041a\u043e\u0434\u041e\u0448"
})
public class Ф0409303ПояснениеОшибок {

    @XmlElement(name = "\u041f\u043e\u044f\u0441\u043d\u0435\u043d\u0438\u0435\u041a\u043e\u0434\u041e\u0448", required = true)
    protected List<Ф0409303ПояснениеОшибокПояснениеКодОш> пояснениеКодОш;

    /**
     * Gets the value of the пояснениеКодОш property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the пояснениеКодОш property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getПояснениеКодОш().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303ПояснениеОшибокПояснениеКодОш }
     * 
     * 
     */
    public List<Ф0409303ПояснениеОшибокПояснениеКодОш> getПояснениеКодОш() {
        if (пояснениеКодОш == null) {
            пояснениеКодОш = new ArrayList<Ф0409303ПояснениеОшибокПояснениеКодОш>();
        }
        return this.пояснениеКодОш;
    }

}
