//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорТраншР5т complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорТраншР5т"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р5_1" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р5_3" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2положит-лок" /&gt;
 *       &lt;attribute name="Р5_4" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка3с-лок" /&gt;
 *       &lt;attribute name="Р5_5" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка5ц-лок" /&gt;
 *       &lt;attribute name="Р5_6" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2положит-лок" /&gt;
 *       &lt;attribute name="Р5_7" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка3с-лок" /&gt;
 *       &lt;attribute name="Р5_8" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2положит-лок" /&gt;
 *       &lt;attribute name="Р5_9" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка3с-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u0422\u0440\u0430\u043d\u0448\u04205\u0442")
public class Ф0409303Данные303ДоговорТраншР5Т {

    @XmlAttribute(name = "\u04205_1")
    protected XMLGregorianCalendar р51;
    @XmlAttribute(name = "\u04205_3")
    protected BigDecimal р53;
    @XmlAttribute(name = "\u04205_4")
    protected String р54;
    @XmlAttribute(name = "\u04205_5")
    protected String р55;
    @XmlAttribute(name = "\u04205_6")
    protected BigDecimal р56;
    @XmlAttribute(name = "\u04205_7")
    protected String р57;
    @XmlAttribute(name = "\u04205_8")
    protected BigDecimal р58;
    @XmlAttribute(name = "\u04205_9")
    protected String р59;

    /**
     * Gets the value of the р51 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР51() {
        return р51;
    }

    /**
     * Sets the value of the р51 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР51(XMLGregorianCalendar value) {
        this.р51 = value;
    }

    /**
     * Gets the value of the р53 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР53() {
        return р53;
    }

    /**
     * Sets the value of the р53 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР53(BigDecimal value) {
        this.р53 = value;
    }

    /**
     * Gets the value of the р54 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР54() {
        return р54;
    }

    /**
     * Sets the value of the р54 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР54(String value) {
        this.р54 = value;
    }

    /**
     * Gets the value of the р55 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР55() {
        return р55;
    }

    /**
     * Sets the value of the р55 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР55(String value) {
        this.р55 = value;
    }

    /**
     * Gets the value of the р56 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР56() {
        return р56;
    }

    /**
     * Sets the value of the р56 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР56(BigDecimal value) {
        this.р56 = value;
    }

    /**
     * Gets the value of the р57 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР57() {
        return р57;
    }

    /**
     * Sets the value of the р57 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР57(String value) {
        this.р57 = value;
    }

    /**
     * Gets the value of the р58 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР58() {
        return р58;
    }

    /**
     * Sets the value of the р58 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР58(BigDecimal value) {
        this.р58 = value;
    }

    /**
     * Gets the value of the р59 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР59() {
        return р59;
    }

    /**
     * Sets the value of the р59 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР59(String value) {
        this.р59 = value;
    }

}
