//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорТраншИстТ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорТраншИстТ"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ИстСум" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншИстТИстСум" maxOccurs="99" minOccurs="0"/&gt;
 *         &lt;element name="ИстДог" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншИстТИстДог" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Р9_10" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u0422\u0440\u0430\u043d\u0448\u0418\u0441\u0442\u0422", propOrder = {
    "\u0438\u0441\u0442\u0421\u0443\u043c",
    "\u0438\u0441\u0442\u0414\u043e\u0433"
})
public class Ф0409303Данные303ДоговорТраншИстТ {

    @XmlElement(name = "\u0418\u0441\u0442\u0421\u0443\u043c")
    protected List<Ф0409303Данные303ДоговорТраншИстТИстСум> истСум;
    @XmlElement(name = "\u0418\u0441\u0442\u0414\u043e\u0433")
    protected List<Ф0409303Данные303ДоговорТраншИстТИстДог> истДог;
    @XmlAttribute(name = "\u04209_10", required = true)
    protected String р910;

    /**
     * Gets the value of the истСум property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the истСум property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getИстСум().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорТраншИстТИстСум }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорТраншИстТИстСум> getИстСум() {
        if (истСум == null) {
            истСум = new ArrayList<Ф0409303Данные303ДоговорТраншИстТИстСум>();
        }
        return this.истСум;
    }

    /**
     * Gets the value of the истДог property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the истДог property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getИстДог().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорТраншИстТИстДог }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорТраншИстТИстДог> getИстДог() {
        if (истДог == null) {
            истДог = new ArrayList<Ф0409303Данные303ДоговорТраншИстТИстДог>();
        }
        return this.истДог;
    }

    /**
     * Gets the value of the р910 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР910() {
        return р910;
    }

    /**
     * Sets the value of the р910 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР910(String value) {
        this.р910 = value;
    }

}
