//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303ИнфПК complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303ИнфПК"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ИмяПК" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаНепустая" /&gt;
 *       &lt;attribute name="НомерВерсииМета" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаНепустая" /&gt;
 *       &lt;attribute name="ДатаВерсииМета" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="НомерВерсииПК" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаНепустая" /&gt;
 *       &lt;attribute name="ДатаВерсииПК" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0418\u043d\u0444\u041f\u041a")
public class Ф0409303ИнфПК {

    @XmlAttribute(name = "\u0418\u043c\u044f\u041f\u041a", required = true)
    protected String имяПК;
    @XmlAttribute(name = "\u041d\u043e\u043c\u0435\u0440\u0412\u0435\u0440\u0441\u0438\u0438\u041c\u0435\u0442\u0430")
    protected String номерВерсииМета;
    @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0412\u0435\u0440\u0441\u0438\u0438\u041c\u0435\u0442\u0430")
    protected XMLGregorianCalendar датаВерсииМета;
    @XmlAttribute(name = "\u041d\u043e\u043c\u0435\u0440\u0412\u0435\u0440\u0441\u0438\u0438\u041f\u041a")
    protected String номерВерсииПК;
    @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0412\u0435\u0440\u0441\u0438\u0438\u041f\u041a")
    protected XMLGregorianCalendar датаВерсииПК;

    /**
     * Gets the value of the имяПК property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИмяПК() {
        return имяПК;
    }

    /**
     * Sets the value of the имяПК property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИмяПК(String value) {
        this.имяПК = value;
    }

    /**
     * Gets the value of the номерВерсииМета property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНомерВерсииМета() {
        return номерВерсииМета;
    }

    /**
     * Sets the value of the номерВерсииМета property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНомерВерсииМета(String value) {
        this.номерВерсииМета = value;
    }

    /**
     * Gets the value of the датаВерсииМета property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДатаВерсииМета() {
        return датаВерсииМета;
    }

    /**
     * Sets the value of the датаВерсииМета property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДатаВерсииМета(XMLGregorianCalendar value) {
        this.датаВерсииМета = value;
    }

    /**
     * Gets the value of the номерВерсииПК property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getНомерВерсииПК() {
        return номерВерсииПК;
    }

    /**
     * Sets the value of the номерВерсииПК property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setНомерВерсииПК(String value) {
        this.номерВерсииПК = value;
    }

    /**
     * Gets the value of the датаВерсииПК property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДатаВерсииПК() {
        return датаВерсииПК;
    }

    /**
     * Sets the value of the датаВерсииПК property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДатаВерсииПК(XMLGregorianCalendar value) {
        this.датаВерсииПК = value;
    }

}
