//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорР2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорР2"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р2_2" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаДо100Непустая-лок" /&gt;
 *       &lt;attribute name="Р2_3" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р2_4" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаДо100Непустая-лок" /&gt;
 *       &lt;attribute name="Р2_5" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р2_6" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка255Непустая" /&gt;
 *       &lt;attribute name="Р2_7" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОГРН_ЮЛ_ИП-лок" /&gt;
 *       &lt;attribute name="Р2_8" type="{urn:cbr-ru:rep0409303:v4.0.4.5}РегНомерКОТип" /&gt;
 *       &lt;attribute name="Р2_9" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОКСМтип" /&gt;
 *       &lt;attribute name="Р2_10" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Целое3неотриц-лок" /&gt;
 *       &lt;attribute name="Р2_11н"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка1с-лок"&gt;
 *             &lt;enumeration value="Б"/&gt;
 *             &lt;enumeration value="Л"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Р2_12н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р2_13н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р2_21" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка255Непустая" /&gt;
 *       &lt;attribute name="Р2_22" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Иден_УИД-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u04202")
public class Ф0409303Данные303ДоговорР2 {

    @XmlAttribute(name = "\u04202_2", required = true)
    protected String р22;
    @XmlAttribute(name = "\u04202_3", required = true)
    protected XMLGregorianCalendar р23;
    @XmlAttribute(name = "\u04202_4")
    protected String р24;
    @XmlAttribute(name = "\u04202_5")
    protected XMLGregorianCalendar р25;
    @XmlAttribute(name = "\u04202_6")
    protected String р26;
    @XmlAttribute(name = "\u04202_7")
    protected String р27;
    @XmlAttribute(name = "\u04202_8")
    protected String р28;
    @XmlAttribute(name = "\u04202_9")
    protected String р29;
    @XmlAttribute(name = "\u04202_10")
    protected BigInteger р210;
    @XmlAttribute(name = "\u04202_11\u043d")
    protected String р211Н;
    @XmlAttribute(name = "\u04202_12\u043d")
    protected XMLGregorianCalendar р212Н;
    @XmlAttribute(name = "\u04202_13\u043d")
    protected XMLGregorianCalendar р213Н;
    @XmlAttribute(name = "\u04202_21")
    protected String р221;
    @XmlAttribute(name = "\u04202_22")
    protected String р222;

    /**
     * Gets the value of the р22 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР22() {
        return р22;
    }

    /**
     * Sets the value of the р22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР22(String value) {
        this.р22 = value;
    }

    /**
     * Gets the value of the р23 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР23() {
        return р23;
    }

    /**
     * Sets the value of the р23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР23(XMLGregorianCalendar value) {
        this.р23 = value;
    }

    /**
     * Gets the value of the р24 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР24() {
        return р24;
    }

    /**
     * Sets the value of the р24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР24(String value) {
        this.р24 = value;
    }

    /**
     * Gets the value of the р25 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР25() {
        return р25;
    }

    /**
     * Sets the value of the р25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР25(XMLGregorianCalendar value) {
        this.р25 = value;
    }

    /**
     * Gets the value of the р26 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР26() {
        return р26;
    }

    /**
     * Sets the value of the р26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР26(String value) {
        this.р26 = value;
    }

    /**
     * Gets the value of the р27 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР27() {
        return р27;
    }

    /**
     * Sets the value of the р27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР27(String value) {
        this.р27 = value;
    }

    /**
     * Gets the value of the р28 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР28() {
        return р28;
    }

    /**
     * Sets the value of the р28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР28(String value) {
        this.р28 = value;
    }

    /**
     * Gets the value of the р29 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР29() {
        return р29;
    }

    /**
     * Sets the value of the р29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР29(String value) {
        this.р29 = value;
    }

    /**
     * Gets the value of the р210 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getР210() {
        return р210;
    }

    /**
     * Sets the value of the р210 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setР210(BigInteger value) {
        this.р210 = value;
    }

    /**
     * Gets the value of the р211Н property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР211Н() {
        return р211Н;
    }

    /**
     * Sets the value of the р211Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР211Н(String value) {
        this.р211Н = value;
    }

    /**
     * Gets the value of the р212Н property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР212Н() {
        return р212Н;
    }

    /**
     * Sets the value of the р212Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР212Н(XMLGregorianCalendar value) {
        this.р212Н = value;
    }

    /**
     * Gets the value of the р213Н property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР213Н() {
        return р213Н;
    }

    /**
     * Sets the value of the р213Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР213Н(XMLGregorianCalendar value) {
        this.р213Н = value;
    }

    /**
     * Gets the value of the р221 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР221() {
        return р221;
    }

    /**
     * Sets the value of the р221 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР221(String value) {
        this.р221 = value;
    }

    /**
     * Gets the value of the р222 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР222() {
        return р222;
    }

    /**
     * Sets the value of the р222 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР222(String value) {
        this.р222 = value;
    }

}
