//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Составитель complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Составитель"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Руководитель" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303СоставительРуководитель"/&gt;
 *         &lt;element name="ГлавБух" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303СоставительГлавБух"/&gt;
 *         &lt;element name="Исполнитель" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303СоставительИсполнитель"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ВидОрг" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ВидОргТип" /&gt;
 *       &lt;attribute name="КодОрг" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}КодОргТип" /&gt;
 *       &lt;attribute name="КодТУ" type="{urn:cbr-ru:rep0409303:v4.0.4.5}КПтип" /&gt;
 *       &lt;attribute name="БИК" type="{urn:cbr-ru:rep0409303:v4.0.4.5}БИКтип" /&gt;
 *       &lt;attribute name="ОКАТО" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОКАТОтип" /&gt;
 *       &lt;attribute name="ОКПО" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОКПОтип" /&gt;
 *       &lt;attribute name="ОГРН" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОГРНтип" /&gt;
 *       &lt;attribute name="СокрНаимен" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка" /&gt;
 *       &lt;attribute name="Адрес" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка" /&gt;
 *       &lt;attribute name="ДатаПодписания" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0421\u043e\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c", propOrder = {
    "\u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c",
    "\u0433\u043b\u0430\u0432\u0411\u0443\u0445",
    "\u0438\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c"
})
public class Ф0409303Составитель {

    @XmlElement(name = "\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c", required = true)
    protected Ф0409303СоставительРуководитель руководитель;
    @XmlElement(name = "\u0413\u043b\u0430\u0432\u0411\u0443\u0445", required = true)
    protected Ф0409303СоставительГлавБух главБух;
    @XmlElement(name = "\u0418\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c", required = true)
    protected Ф0409303СоставительИсполнитель исполнитель;
    @XmlAttribute(name = "\u0412\u0438\u0434\u041e\u0440\u0433", required = true)
    protected ВидОргТип видОрг;
    @XmlAttribute(name = "\u041a\u043e\u0434\u041e\u0440\u0433", required = true)
    protected String кодОрг;
    @XmlAttribute(name = "\u041a\u043e\u0434\u0422\u0423")
    protected String кодТУ;
    @XmlAttribute(name = "\u0411\u0418\u041a")
    protected String бик;
    @XmlAttribute(name = "\u041e\u041a\u0410\u0422\u041e")
    protected String окато;
    @XmlAttribute(name = "\u041e\u041a\u041f\u041e")
    protected String окпо;
    @XmlAttribute(name = "\u041e\u0413\u0420\u041d")
    protected String огрн;
    @XmlAttribute(name = "\u0421\u043e\u043a\u0440\u041d\u0430\u0438\u043c\u0435\u043d")
    protected String сокрНаимен;
    @XmlAttribute(name = "\u0410\u0434\u0440\u0435\u0441")
    protected String адрес;
    @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0438\u044f", required = true)
    protected XMLGregorianCalendar датаПодписания;

    /**
     * Gets the value of the руководитель property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303СоставительРуководитель }
     *     
     */
    public Ф0409303СоставительРуководитель getРуководитель() {
        return руководитель;
    }

    /**
     * Sets the value of the руководитель property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303СоставительРуководитель }
     *     
     */
    public void setРуководитель(Ф0409303СоставительРуководитель value) {
        this.руководитель = value;
    }

    /**
     * Gets the value of the главБух property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303СоставительГлавБух }
     *     
     */
    public Ф0409303СоставительГлавБух getГлавБух() {
        return главБух;
    }

    /**
     * Sets the value of the главБух property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303СоставительГлавБух }
     *     
     */
    public void setГлавБух(Ф0409303СоставительГлавБух value) {
        this.главБух = value;
    }

    /**
     * Gets the value of the исполнитель property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303СоставительИсполнитель }
     *     
     */
    public Ф0409303СоставительИсполнитель getИсполнитель() {
        return исполнитель;
    }

    /**
     * Sets the value of the исполнитель property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303СоставительИсполнитель }
     *     
     */
    public void setИсполнитель(Ф0409303СоставительИсполнитель value) {
        this.исполнитель = value;
    }

    /**
     * Gets the value of the видОрг property.
     * 
     * @return
     *     possible object is
     *     {@link ВидОргТип }
     *     
     */
    public ВидОргТип getВидОрг() {
        return видОрг;
    }

    /**
     * Sets the value of the видОрг property.
     * 
     * @param value
     *     allowed object is
     *     {@link ВидОргТип }
     *     
     */
    public void setВидОрг(ВидОргТип value) {
        this.видОрг = value;
    }

    /**
     * Gets the value of the кодОрг property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКодОрг() {
        return кодОрг;
    }

    /**
     * Sets the value of the кодОрг property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКодОрг(String value) {
        this.кодОрг = value;
    }

    /**
     * Gets the value of the кодТУ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКодТУ() {
        return кодТУ;
    }

    /**
     * Sets the value of the кодТУ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКодТУ(String value) {
        this.кодТУ = value;
    }

    /**
     * Gets the value of the бик property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getБИК() {
        return бик;
    }

    /**
     * Sets the value of the бик property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setБИК(String value) {
        this.бик = value;
    }

    /**
     * Gets the value of the окато property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОКАТО() {
        return окато;
    }

    /**
     * Sets the value of the окато property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОКАТО(String value) {
        this.окато = value;
    }

    /**
     * Gets the value of the окпо property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОКПО() {
        return окпо;
    }

    /**
     * Sets the value of the окпо property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОКПО(String value) {
        this.окпо = value;
    }

    /**
     * Gets the value of the огрн property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОГРН() {
        return огрн;
    }

    /**
     * Sets the value of the огрн property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОГРН(String value) {
        this.огрн = value;
    }

    /**
     * Gets the value of the сокрНаимен property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getСокрНаимен() {
        return сокрНаимен;
    }

    /**
     * Sets the value of the сокрНаимен property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setСокрНаимен(String value) {
        this.сокрНаимен = value;
    }

    /**
     * Gets the value of the адрес property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getАдрес() {
        return адрес;
    }

    /**
     * Sets the value of the адрес property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setАдрес(String value) {
        this.адрес = value;
    }

    /**
     * Gets the value of the датаПодписания property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДатаПодписания() {
        return датаПодписания;
    }

    /**
     * Sets the value of the датаПодписания property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДатаПодписания(XMLGregorianCalendar value) {
        this.датаПодписания = value;
    }

}
