//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303Договор complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303Договор"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Р1" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР1"/&gt;
 *         &lt;element name="Р2" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР2"/&gt;
 *         &lt;element name="Р3" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР3"/&gt;
 *         &lt;element name="Р5" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР5" minOccurs="0"/&gt;
 *         &lt;element name="Р6" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР6" minOccurs="0"/&gt;
 *         &lt;element name="Р7" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР7" minOccurs="0"/&gt;
 *         &lt;element name="Р8" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР8" minOccurs="0"/&gt;
 *         &lt;element name="Р9" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР9" minOccurs="0"/&gt;
 *         &lt;element name="Усл" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорУсл" maxOccurs="99" minOccurs="0"/&gt;
 *         &lt;element name="Р4Обесп" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР4Обесп" maxOccurs="99" minOccurs="0"/&gt;
 *         &lt;element name="НеА" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорНеА" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="Погшн" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорПогшн" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Ист" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорИст" maxOccurs="99" minOccurs="0"/&gt;
 *         &lt;element name="Р1ГВЗ" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР1ГВЗ" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Р2Обрем" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР2Обрем" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Р10" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорР10" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Транш" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТранш" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Р2_1" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Иден-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440", propOrder = {
    "\u04401",
    "\u04402",
    "\u04403",
    "\u04405",
    "\u04406",
    "\u04407",
    "\u04408",
    "\u04409",
    "\u0443\u0441\u043b",
    "\u04404\u041e\u0431\u0435\u0441\u043f",
    "\u043d\u0435\u0410",
    "\u043f\u043e\u0433\u0448\u043d",
    "\u0438\u0441\u0442",
    "\u04401\u0413\u0412\u0417",
    "\u04402\u041e\u0431\u0440\u0435\u043c",
    "\u044010",
    "\u0442\u0440\u0430\u043d\u0448"
})
public class Ф0409303Данные303Договор {

    @XmlElement(name = "\u04201", required = true)
    protected Ф0409303Данные303ДоговорР1 р1;
    @XmlElement(name = "\u04202", required = true)
    protected Ф0409303Данные303ДоговорР2 р2;
    @XmlElement(name = "\u04203", required = true)
    protected Ф0409303Данные303ДоговорР3 р3;
    @XmlElement(name = "\u04205")
    protected Ф0409303Данные303ДоговорР5 р5;
    @XmlElement(name = "\u04206")
    protected Ф0409303Данные303ДоговорР6 р6;
    @XmlElement(name = "\u04207")
    protected Ф0409303Данные303ДоговорР7 р7;
    @XmlElement(name = "\u04208")
    protected Ф0409303Данные303ДоговорР8 р8;
    @XmlElement(name = "\u04209")
    protected Ф0409303Данные303ДоговорР9 р9;
    @XmlElement(name = "\u0423\u0441\u043b")
    protected List<Ф0409303Данные303ДоговорУсл> усл;
    @XmlElement(name = "\u04204\u041e\u0431\u0435\u0441\u043f")
    protected List<Ф0409303Данные303ДоговорР4Обесп> р4Обесп;
    @XmlElement(name = "\u041d\u0435\u0410")
    protected List<Ф0409303Данные303ДоговорНеА> неА;
    @XmlElement(name = "\u041f\u043e\u0433\u0448\u043d")
    protected List<Ф0409303Данные303ДоговорПогшн> погшн;
    @XmlElement(name = "\u0418\u0441\u0442")
    protected List<Ф0409303Данные303ДоговорИст> ист;
    @XmlElement(name = "\u04201\u0413\u0412\u0417")
    protected List<Ф0409303Данные303ДоговорР1ГВЗ> р1ГВЗ;
    @XmlElement(name = "\u04202\u041e\u0431\u0440\u0435\u043c")
    protected List<Ф0409303Данные303ДоговорР2Обрем> р2Обрем;
    @XmlElement(name = "\u042010")
    protected List<Ф0409303Данные303ДоговорР10> р10;
    @XmlElement(name = "\u0422\u0440\u0430\u043d\u0448")
    protected List<Ф0409303Данные303ДоговорТранш> транш;
    @XmlAttribute(name = "\u04202_1", required = true)
    protected String р21;

    /**
     * Gets the value of the р1 property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорР1 }
     *     
     */
    public Ф0409303Данные303ДоговорР1 getР1() {
        return р1;
    }

    /**
     * Sets the value of the р1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорР1 }
     *     
     */
    public void setР1(Ф0409303Данные303ДоговорР1 value) {
        this.р1 = value;
    }

    /**
     * Gets the value of the р2 property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорР2 }
     *     
     */
    public Ф0409303Данные303ДоговорР2 getР2() {
        return р2;
    }

    /**
     * Sets the value of the р2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорР2 }
     *     
     */
    public void setР2(Ф0409303Данные303ДоговорР2 value) {
        this.р2 = value;
    }

    /**
     * Gets the value of the р3 property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорР3 }
     *     
     */
    public Ф0409303Данные303ДоговорР3 getР3() {
        return р3;
    }

    /**
     * Sets the value of the р3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорР3 }
     *     
     */
    public void setР3(Ф0409303Данные303ДоговорР3 value) {
        this.р3 = value;
    }

    /**
     * Gets the value of the р5 property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорР5 }
     *     
     */
    public Ф0409303Данные303ДоговорР5 getР5() {
        return р5;
    }

    /**
     * Sets the value of the р5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорР5 }
     *     
     */
    public void setР5(Ф0409303Данные303ДоговорР5 value) {
        this.р5 = value;
    }

    /**
     * Gets the value of the р6 property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорР6 }
     *     
     */
    public Ф0409303Данные303ДоговорР6 getР6() {
        return р6;
    }

    /**
     * Sets the value of the р6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорР6 }
     *     
     */
    public void setР6(Ф0409303Данные303ДоговорР6 value) {
        this.р6 = value;
    }

    /**
     * Gets the value of the р7 property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорР7 }
     *     
     */
    public Ф0409303Данные303ДоговорР7 getР7() {
        return р7;
    }

    /**
     * Sets the value of the р7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорР7 }
     *     
     */
    public void setР7(Ф0409303Данные303ДоговорР7 value) {
        this.р7 = value;
    }

    /**
     * Gets the value of the р8 property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорР8 }
     *     
     */
    public Ф0409303Данные303ДоговорР8 getР8() {
        return р8;
    }

    /**
     * Sets the value of the р8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорР8 }
     *     
     */
    public void setР8(Ф0409303Данные303ДоговорР8 value) {
        this.р8 = value;
    }

    /**
     * Gets the value of the р9 property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорР9 }
     *     
     */
    public Ф0409303Данные303ДоговорР9 getР9() {
        return р9;
    }

    /**
     * Sets the value of the р9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорР9 }
     *     
     */
    public void setР9(Ф0409303Данные303ДоговорР9 value) {
        this.р9 = value;
    }

    /**
     * Gets the value of the усл property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the усл property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getУсл().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорУсл }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорУсл> getУсл() {
        if (усл == null) {
            усл = new ArrayList<Ф0409303Данные303ДоговорУсл>();
        }
        return this.усл;
    }

    /**
     * Gets the value of the р4Обесп property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the р4Обесп property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getР4Обесп().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорР4Обесп }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорР4Обесп> getР4Обесп() {
        if (р4Обесп == null) {
            р4Обесп = new ArrayList<Ф0409303Данные303ДоговорР4Обесп>();
        }
        return this.р4Обесп;
    }

    /**
     * Gets the value of the неА property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the неА property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getНеА().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорНеА }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорНеА> getНеА() {
        if (неА == null) {
            неА = new ArrayList<Ф0409303Данные303ДоговорНеА>();
        }
        return this.неА;
    }

    /**
     * Gets the value of the погшн property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the погшн property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getПогшн().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорПогшн }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорПогшн> getПогшн() {
        if (погшн == null) {
            погшн = new ArrayList<Ф0409303Данные303ДоговорПогшн>();
        }
        return this.погшн;
    }

    /**
     * Gets the value of the ист property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the ист property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getИст().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорИст }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорИст> getИст() {
        if (ист == null) {
            ист = new ArrayList<Ф0409303Данные303ДоговорИст>();
        }
        return this.ист;
    }

    /**
     * Gets the value of the р1ГВЗ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the р1ГВЗ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getР1ГВЗ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорР1ГВЗ }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорР1ГВЗ> getР1ГВЗ() {
        if (р1ГВЗ == null) {
            р1ГВЗ = new ArrayList<Ф0409303Данные303ДоговорР1ГВЗ>();
        }
        return this.р1ГВЗ;
    }

    /**
     * Gets the value of the р2Обрем property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the р2Обрем property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getР2Обрем().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорР2Обрем }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорР2Обрем> getР2Обрем() {
        if (р2Обрем == null) {
            р2Обрем = new ArrayList<Ф0409303Данные303ДоговорР2Обрем>();
        }
        return this.р2Обрем;
    }

    /**
     * Gets the value of the р10 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the р10 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getР10().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорР10 }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорР10> getР10() {
        if (р10 == null) {
            р10 = new ArrayList<Ф0409303Данные303ДоговорР10>();
        }
        return this.р10;
    }

    /**
     * Gets the value of the транш property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the транш property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getТранш().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорТранш }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорТранш> getТранш() {
        if (транш == null) {
            транш = new ArrayList<Ф0409303Данные303ДоговорТранш>();
        }
        return this.транш;
    }

    /**
     * Gets the value of the р21 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР21() {
        return р21;
    }

    /**
     * Sets the value of the р21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР21(String value) {
        this.р21 = value;
    }

}
