//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорР9 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорР9"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р9_1" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок" /&gt;
 *       &lt;attribute name="Р9_2" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р9_3" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р9_4" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок" /&gt;
 *       &lt;attribute name="Р9_5" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2-лок" /&gt;
 *       &lt;attribute name="Р9_6" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2-лок" /&gt;
 *       &lt;attribute name="Р9_7" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р9_8" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р9_13" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка3с-лок" /&gt;
 *       &lt;attribute name="Р9_14" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка3с-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u04209")
public class Ф0409303Данные303ДоговорР9 {

    @XmlAttribute(name = "\u04209_1")
    protected String р91;
    @XmlAttribute(name = "\u04209_2")
    protected BigDecimal р92;
    @XmlAttribute(name = "\u04209_3")
    protected BigDecimal р93;
    @XmlAttribute(name = "\u04209_4")
    protected String р94;
    @XmlAttribute(name = "\u04209_5")
    protected BigDecimal р95;
    @XmlAttribute(name = "\u04209_6")
    protected BigDecimal р96;
    @XmlAttribute(name = "\u04209_7")
    protected BigDecimal р97;
    @XmlAttribute(name = "\u04209_8")
    protected XMLGregorianCalendar р98;
    @XmlAttribute(name = "\u04209_13")
    protected String р913;
    @XmlAttribute(name = "\u04209_14")
    protected String р914;

    /**
     * Gets the value of the р91 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР91() {
        return р91;
    }

    /**
     * Sets the value of the р91 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР91(String value) {
        this.р91 = value;
    }

    /**
     * Gets the value of the р92 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР92() {
        return р92;
    }

    /**
     * Sets the value of the р92 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР92(BigDecimal value) {
        this.р92 = value;
    }

    /**
     * Gets the value of the р93 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР93() {
        return р93;
    }

    /**
     * Sets the value of the р93 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР93(BigDecimal value) {
        this.р93 = value;
    }

    /**
     * Gets the value of the р94 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР94() {
        return р94;
    }

    /**
     * Sets the value of the р94 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР94(String value) {
        this.р94 = value;
    }

    /**
     * Gets the value of the р95 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР95() {
        return р95;
    }

    /**
     * Sets the value of the р95 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР95(BigDecimal value) {
        this.р95 = value;
    }

    /**
     * Gets the value of the р96 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР96() {
        return р96;
    }

    /**
     * Sets the value of the р96 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР96(BigDecimal value) {
        this.р96 = value;
    }

    /**
     * Gets the value of the р97 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР97() {
        return р97;
    }

    /**
     * Sets the value of the р97 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР97(BigDecimal value) {
        this.р97 = value;
    }

    /**
     * Gets the value of the р98 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР98() {
        return р98;
    }

    /**
     * Sets the value of the р98 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР98(XMLGregorianCalendar value) {
        this.р98 = value;
    }

    /**
     * Gets the value of the р913 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР913() {
        return р913;
    }

    /**
     * Sets the value of the р913 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР913(String value) {
        this.р913 = value;
    }

    /**
     * Gets the value of the р914 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР914() {
        return р914;
    }

    /**
     * Sets the value of the р914 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР914(String value) {
        this.р914 = value;
    }

}
