//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for Ф0409303 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Составитель" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Составитель"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Данные303" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303"/&gt;
 *           &lt;element name="НетДанных" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303НетДанных"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="Пояснение" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Пояснение" minOccurs="0"/&gt;
 *         &lt;element name="ПротоколКонтроля" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303ПротоколКонтроля" minOccurs="0"/&gt;
 *         &lt;element name="ПояснениеОшибок" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303ПояснениеОшибок" minOccurs="0"/&gt;
 *         &lt;element name="ИнфПК" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303ИнфПК" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="УникИдОЭС" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}GUIDтип" /&gt;
 *       &lt;attribute name="ВидОЭС" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ВидОЭСтип" /&gt;
 *       &lt;attribute name="КодФормы" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаНепустая" /&gt;
 *       &lt;attribute name="ОКУД" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОКУДтип" /&gt;
 *       &lt;attribute name="ВидОтчета" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка" /&gt;
 *       &lt;attribute name="ОтчДата" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Периодичность" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ТипПериодаТип" /&gt;
 *       &lt;attribute name="ДатаВремяФормирования" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ДатаВремя" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace = "urn:cbr-ru:rep0409303:v4.0.4.5" , name = "\u04240409303")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303", propOrder = {
    "\u0441\u043e\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c",
    "\u0434\u0430\u043d\u043d\u044b\u0435303",
    "\u043d\u0435\u0442\u0414\u0430\u043d\u043d\u044b\u0445",
    "\u043f\u043e\u044f\u0441\u043d\u0435\u043d\u0438\u0435",
    "\u043f\u0440\u043e\u0442\u043e\u043a\u043e\u043b\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044f",
    "\u043f\u043e\u044f\u0441\u043d\u0435\u043d\u0438\u0435\u041e\u0448\u0438\u0431\u043e\u043a",
    "\u0438\u043d\u0444\u041f\u041a"
})
public class Ф0409303 {

    @XmlElement(name = "\u0421\u043e\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c", required = true)
    protected Ф0409303Составитель составитель;
    @XmlElement(name = "\u0414\u0430\u043d\u043d\u044b\u0435303")
    protected Ф0409303Данные303 данные303;
    @XmlElement(name = "\u041d\u0435\u0442\u0414\u0430\u043d\u043d\u044b\u0445")
    protected Ф0409303НетДанных нетДанных;
    @XmlElement(name = "\u041f\u043e\u044f\u0441\u043d\u0435\u043d\u0438\u0435")
    protected Ф0409303Пояснение пояснение;
    @XmlElement(name = "\u041f\u0440\u043e\u0442\u043e\u043a\u043e\u043b\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044f")
    protected Ф0409303ПротоколКонтроля протоколКонтроля;
    @XmlElement(name = "\u041f\u043e\u044f\u0441\u043d\u0435\u043d\u0438\u0435\u041e\u0448\u0438\u0431\u043e\u043a")
    protected Ф0409303ПояснениеОшибок пояснениеОшибок;
    @XmlElement(name = "\u0418\u043d\u0444\u041f\u041a")
    protected Ф0409303ИнфПК инфПК;
    @XmlAttribute(name = "\u0423\u043d\u0438\u043a\u0418\u0434\u041e\u042d\u0421", required = true)
    protected String уникИдОЭС;
    @XmlAttribute(name = "\u0412\u0438\u0434\u041e\u042d\u0421", required = true)
    protected ВидОЭСтип видОЭС;
    @XmlAttribute(name = "\u041a\u043e\u0434\u0424\u043e\u0440\u043c\u044b", required = true)
    protected String кодФормы;
    @XmlAttribute(name = "\u041e\u041a\u0423\u0414")
    protected String окуд;
    @XmlAttribute(name = "\u0412\u0438\u0434\u041e\u0442\u0447\u0435\u0442\u0430", required = true)
    protected String видОтчета;
    @XmlAttribute(name = "\u041e\u0442\u0447\u0414\u0430\u0442\u0430", required = true)
    protected XMLGregorianCalendar отчДата;
    @XmlAttribute(name = "\u041f\u0435\u0440\u0438\u043e\u0434\u0438\u0447\u043d\u043e\u0441\u0442\u044c", required = true)
    protected ТипПериодаТип периодичность;
    @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0412\u0440\u0435\u043c\u044f\u0424\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f", required = true)
    protected XMLGregorianCalendar датаВремяФормирования;

    /**
     * Gets the value of the составитель property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Составитель }
     *     
     */
    public Ф0409303Составитель getСоставитель() {
        return составитель;
    }

    /**
     * Sets the value of the составитель property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Составитель }
     *     
     */
    public void setСоставитель(Ф0409303Составитель value) {
        this.составитель = value;
    }

    /**
     * Gets the value of the данные303 property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303 }
     *     
     */
    public Ф0409303Данные303 getДанные303() {
        return данные303;
    }

    /**
     * Sets the value of the данные303 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303 }
     *     
     */
    public void setДанные303(Ф0409303Данные303 value) {
        this.данные303 = value;
    }

    /**
     * Gets the value of the нетДанных property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303НетДанных }
     *     
     */
    public Ф0409303НетДанных getНетДанных() {
        return нетДанных;
    }

    /**
     * Sets the value of the нетДанных property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303НетДанных }
     *     
     */
    public void setНетДанных(Ф0409303НетДанных value) {
        this.нетДанных = value;
    }

    /**
     * Gets the value of the пояснение property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Пояснение }
     *     
     */
    public Ф0409303Пояснение getПояснение() {
        return пояснение;
    }

    /**
     * Sets the value of the пояснение property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Пояснение }
     *     
     */
    public void setПояснение(Ф0409303Пояснение value) {
        this.пояснение = value;
    }

    /**
     * Gets the value of the протоколКонтроля property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303ПротоколКонтроля }
     *     
     */
    public Ф0409303ПротоколКонтроля getПротоколКонтроля() {
        return протоколКонтроля;
    }

    /**
     * Sets the value of the протоколКонтроля property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303ПротоколКонтроля }
     *     
     */
    public void setПротоколКонтроля(Ф0409303ПротоколКонтроля value) {
        this.протоколКонтроля = value;
    }

    /**
     * Gets the value of the пояснениеОшибок property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303ПояснениеОшибок }
     *     
     */
    public Ф0409303ПояснениеОшибок getПояснениеОшибок() {
        return пояснениеОшибок;
    }

    /**
     * Sets the value of the пояснениеОшибок property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303ПояснениеОшибок }
     *     
     */
    public void setПояснениеОшибок(Ф0409303ПояснениеОшибок value) {
        this.пояснениеОшибок = value;
    }

    /**
     * Gets the value of the инфПК property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303ИнфПК }
     *     
     */
    public Ф0409303ИнфПК getИнфПК() {
        return инфПК;
    }

    /**
     * Sets the value of the инфПК property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303ИнфПК }
     *     
     */
    public void setИнфПК(Ф0409303ИнфПК value) {
        this.инфПК = value;
    }

    /**
     * Gets the value of the уникИдОЭС property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getУникИдОЭС() {
        return уникИдОЭС;
    }

    /**
     * Sets the value of the уникИдОЭС property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setУникИдОЭС(String value) {
        this.уникИдОЭС = value;
    }

    /**
     * Gets the value of the видОЭС property.
     * 
     * @return
     *     possible object is
     *     {@link ВидОЭСтип }
     *     
     */
    public ВидОЭСтип getВидОЭС() {
        return видОЭС;
    }

    /**
     * Sets the value of the видОЭС property.
     * 
     * @param value
     *     allowed object is
     *     {@link ВидОЭСтип }
     *     
     */
    public void setВидОЭС(ВидОЭСтип value) {
        this.видОЭС = value;
    }

    /**
     * Gets the value of the кодФормы property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКодФормы() {
        return кодФормы;
    }

    /**
     * Sets the value of the кодФормы property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКодФормы(String value) {
        this.кодФормы = value;
    }

    /**
     * Gets the value of the окуд property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getОКУД() {
        return окуд;
    }

    /**
     * Sets the value of the окуд property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setОКУД(String value) {
        this.окуд = value;
    }

    /**
     * Gets the value of the видОтчета property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getВидОтчета() {
        return видОтчета;
    }

    /**
     * Sets the value of the видОтчета property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setВидОтчета(String value) {
        this.видОтчета = value;
    }

    /**
     * Gets the value of the отчДата property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getОтчДата() {
        return отчДата;
    }

    /**
     * Sets the value of the отчДата property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setОтчДата(XMLGregorianCalendar value) {
        this.отчДата = value;
    }

    /**
     * Gets the value of the периодичность property.
     * 
     * @return
     *     possible object is
     *     {@link ТипПериодаТип }
     *     
     */
    public ТипПериодаТип getПериодичность() {
        return периодичность;
    }

    /**
     * Sets the value of the периодичность property.
     * 
     * @param value
     *     allowed object is
     *     {@link ТипПериодаТип }
     *     
     */
    public void setПериодичность(ТипПериодаТип value) {
        this.периодичность = value;
    }

    /**
     * Gets the value of the датаВремяФормирования property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДатаВремяФормирования() {
        return датаВремяФормирования;
    }

    /**
     * Sets the value of the датаВремяФормирования property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДатаВремяФормирования(XMLGregorianCalendar value) {
        this.датаВремяФормирования = value;
    }

}
