//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорР4Обесп complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорР4Обесп"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р4_1" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок" /&gt;
 *       &lt;attribute name="Р4_2" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р4_3" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *       &lt;attribute name="Р4_4" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р4_5н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р4_6н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u04204\u041e\u0431\u0435\u0441\u043f")
public class Ф0409303Данные303ДоговорР4Обесп {

    @XmlAttribute(name = "\u04204_1")
    protected String р41;
    @XmlAttribute(name = "\u04204_2")
    protected BigDecimal р42;
    @XmlAttribute(name = "\u04204_3")
    protected XMLGregorianCalendar р43;
    @XmlAttribute(name = "\u04204_4")
    protected BigDecimal р44;
    @XmlAttribute(name = "\u04204_5\u043d")
    protected BigDecimal р45Н;
    @XmlAttribute(name = "\u04204_6\u043d")
    protected BigDecimal р46Н;

    /**
     * Gets the value of the р41 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР41() {
        return р41;
    }

    /**
     * Sets the value of the р41 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР41(String value) {
        this.р41 = value;
    }

    /**
     * Gets the value of the р42 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР42() {
        return р42;
    }

    /**
     * Sets the value of the р42 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР42(BigDecimal value) {
        this.р42 = value;
    }

    /**
     * Gets the value of the р43 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР43() {
        return р43;
    }

    /**
     * Sets the value of the р43 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР43(XMLGregorianCalendar value) {
        this.р43 = value;
    }

    /**
     * Gets the value of the р44 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР44() {
        return р44;
    }

    /**
     * Sets the value of the р44 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР44(BigDecimal value) {
        this.р44 = value;
    }

    /**
     * Gets the value of the р45Н property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР45Н() {
        return р45Н;
    }

    /**
     * Sets the value of the р45Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР45Н(BigDecimal value) {
        this.р45Н = value;
    }

    /**
     * Gets the value of the р46Н property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР46Н() {
        return р46Н;
    }

    /**
     * Sets the value of the р46Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР46Н(BigDecimal value) {
        this.р46Н = value;
    }

}
