//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорР8 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорР8"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р8_1" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р8_2" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р8_3" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р8_4" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят3.2неотриц-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u04208")
public class Ф0409303Данные303ДоговорР8 {

    @XmlAttribute(name = "\u04208_1")
    protected BigDecimal р81;
    @XmlAttribute(name = "\u04208_2")
    protected BigDecimal р82;
    @XmlAttribute(name = "\u04208_3")
    protected BigDecimal р83;
    @XmlAttribute(name = "\u04208_4")
    protected BigDecimal р84;

    /**
     * Gets the value of the р81 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР81() {
        return р81;
    }

    /**
     * Sets the value of the р81 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР81(BigDecimal value) {
        this.р81 = value;
    }

    /**
     * Gets the value of the р82 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР82() {
        return р82;
    }

    /**
     * Sets the value of the р82 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР82(BigDecimal value) {
        this.р82 = value;
    }

    /**
     * Gets the value of the р83 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР83() {
        return р83;
    }

    /**
     * Sets the value of the р83 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР83(BigDecimal value) {
        this.р83 = value;
    }

    /**
     * Gets the value of the р84 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР84() {
        return р84;
    }

    /**
     * Sets the value of the р84 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР84(BigDecimal value) {
        this.р84 = value;
    }

}
