//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорР2Обрем complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорР2Обрем"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р2_14н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка255Непустая" /&gt;
 *       &lt;attribute name="Р2_15н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОГРН_ЮЛ_ИП-лок" /&gt;
 *       &lt;attribute name="Р2_16н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Регн_CBRF-лок" /&gt;
 *       &lt;attribute name="Р2_17н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОКСМтип" /&gt;
 *       &lt;attribute name="Р2_18н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок" /&gt;
 *       &lt;attribute name="Р2_19н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2положит-лок" /&gt;
 *       &lt;attribute name="Р2_20н" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u04202\u041e\u0431\u0440\u0435\u043c")
public class Ф0409303Данные303ДоговорР2Обрем {

    @XmlAttribute(name = "\u04202_14\u043d")
    protected String р214Н;
    @XmlAttribute(name = "\u04202_15\u043d")
    protected String р215Н;
    @XmlAttribute(name = "\u04202_16\u043d")
    protected String р216Н;
    @XmlAttribute(name = "\u04202_17\u043d")
    protected String р217Н;
    @XmlAttribute(name = "\u04202_18\u043d")
    protected String р218Н;
    @XmlAttribute(name = "\u04202_19\u043d")
    protected BigDecimal р219Н;
    @XmlAttribute(name = "\u04202_20\u043d")
    protected XMLGregorianCalendar р220Н;

    /**
     * Gets the value of the р214Н property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР214Н() {
        return р214Н;
    }

    /**
     * Sets the value of the р214Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР214Н(String value) {
        this.р214Н = value;
    }

    /**
     * Gets the value of the р215Н property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР215Н() {
        return р215Н;
    }

    /**
     * Sets the value of the р215Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР215Н(String value) {
        this.р215Н = value;
    }

    /**
     * Gets the value of the р216Н property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР216Н() {
        return р216Н;
    }

    /**
     * Sets the value of the р216Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР216Н(String value) {
        this.р216Н = value;
    }

    /**
     * Gets the value of the р217Н property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР217Н() {
        return р217Н;
    }

    /**
     * Sets the value of the р217Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР217Н(String value) {
        this.р217Н = value;
    }

    /**
     * Gets the value of the р218Н property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР218Н() {
        return р218Н;
    }

    /**
     * Sets the value of the р218Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР218Н(String value) {
        this.р218Н = value;
    }

    /**
     * Gets the value of the р219Н property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР219Н() {
        return р219Н;
    }

    /**
     * Sets the value of the р219Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР219Н(BigDecimal value) {
        this.р219Н = value;
    }

    /**
     * Gets the value of the р220Н property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getР220Н() {
        return р220Н;
    }

    /**
     * Sets the value of the р220Н property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setР220Н(XMLGregorianCalendar value) {
        this.р220Н = value;
    }

}
