//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорР10 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорР10"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р10_1" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок" /&gt;
 *       &lt;attribute name="Р10_2" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р10_3" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р10_4" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка255Непустая" /&gt;
 *       &lt;attribute name="Р10_5" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОГРН_ЮЛ_ИП-лок" /&gt;
 *       &lt;attribute name="Р10_6" type="{urn:cbr-ru:rep0409303:v4.0.4.5}РегНомерКОТип" /&gt;
 *       &lt;attribute name="Р10_7" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ОКСМтип" /&gt;
 *       &lt;attribute name="Р10_8" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р10_9" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка3с-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u042010")
public class Ф0409303Данные303ДоговорР10 {

    @XmlAttribute(name = "\u042010_1", required = true)
    protected String р101;
    @XmlAttribute(name = "\u042010_2", required = true)
    protected BigDecimal р102;
    @XmlAttribute(name = "\u042010_3", required = true)
    protected BigDecimal р103;
    @XmlAttribute(name = "\u042010_4", required = true)
    protected String р104;
    @XmlAttribute(name = "\u042010_5")
    protected String р105;
    @XmlAttribute(name = "\u042010_6")
    protected String р106;
    @XmlAttribute(name = "\u042010_7")
    protected String р107;
    @XmlAttribute(name = "\u042010_8")
    protected BigDecimal р108;
    @XmlAttribute(name = "\u042010_9")
    protected String р109;

    /**
     * Gets the value of the р101 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР101() {
        return р101;
    }

    /**
     * Sets the value of the р101 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР101(String value) {
        this.р101 = value;
    }

    /**
     * Gets the value of the р102 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР102() {
        return р102;
    }

    /**
     * Sets the value of the р102 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР102(BigDecimal value) {
        this.р102 = value;
    }

    /**
     * Gets the value of the р103 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР103() {
        return р103;
    }

    /**
     * Sets the value of the р103 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР103(BigDecimal value) {
        this.р103 = value;
    }

    /**
     * Gets the value of the р104 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР104() {
        return р104;
    }

    /**
     * Sets the value of the р104 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР104(String value) {
        this.р104 = value;
    }

    /**
     * Gets the value of the р105 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР105() {
        return р105;
    }

    /**
     * Sets the value of the р105 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР105(String value) {
        this.р105 = value;
    }

    /**
     * Gets the value of the р106 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР106() {
        return р106;
    }

    /**
     * Sets the value of the р106 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР106(String value) {
        this.р106 = value;
    }

    /**
     * Gets the value of the р107 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР107() {
        return р107;
    }

    /**
     * Sets the value of the р107 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР107(String value) {
        this.р107 = value;
    }

    /**
     * Gets the value of the р108 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР108() {
        return р108;
    }

    /**
     * Sets the value of the р108 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР108(BigDecimal value) {
        this.р108 = value;
    }

    /**
     * Gets the value of the р109 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР109() {
        return р109;
    }

    /**
     * Sets the value of the р109 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР109(String value) {
        this.р109 = value;
    }

}
