//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорР6 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорР6"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р6_1" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СчетЛицТип" /&gt;
 *       &lt;attribute name="Р6_2" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СчетЛицТип" /&gt;
 *       &lt;attribute name="Р6_3" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р6_4" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р6_5" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок" /&gt;
 *       &lt;attribute name="Р6_6" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Симв10-Спр-лок" /&gt;
 *       &lt;attribute name="Р6_7" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят3.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р6_8" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р6_9" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Десят20.2неотриц-лок" /&gt;
 *       &lt;attribute name="Р6_10" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка255Непустая" /&gt;
 *       &lt;attribute name="Р6_11" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка2" /&gt;
 *       &lt;attribute name="Р6_12" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка2" /&gt;
 *       &lt;attribute name="Р6_13" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка4с-лок" /&gt;
 *       &lt;attribute name="Р6_14" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Строка2" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u04206")
public class Ф0409303Данные303ДоговорР6 {

    @XmlAttribute(name = "\u04206_1")
    protected String р61;
    @XmlAttribute(name = "\u04206_2")
    protected String р62;
    @XmlAttribute(name = "\u04206_3")
    protected BigDecimal р63;
    @XmlAttribute(name = "\u04206_4")
    protected BigDecimal р64;
    @XmlAttribute(name = "\u04206_5")
    protected String р65;
    @XmlAttribute(name = "\u04206_6")
    protected String р66;
    @XmlAttribute(name = "\u04206_7")
    protected BigDecimal р67;
    @XmlAttribute(name = "\u04206_8")
    protected BigDecimal р68;
    @XmlAttribute(name = "\u04206_9")
    protected BigDecimal р69;
    @XmlAttribute(name = "\u04206_10")
    protected String р610;
    @XmlAttribute(name = "\u04206_11")
    protected String р611;
    @XmlAttribute(name = "\u04206_12")
    protected String р612;
    @XmlAttribute(name = "\u04206_13")
    protected String р613;
    @XmlAttribute(name = "\u04206_14")
    protected String р614;

    /**
     * Gets the value of the р61 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР61() {
        return р61;
    }

    /**
     * Sets the value of the р61 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР61(String value) {
        this.р61 = value;
    }

    /**
     * Gets the value of the р62 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР62() {
        return р62;
    }

    /**
     * Sets the value of the р62 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР62(String value) {
        this.р62 = value;
    }

    /**
     * Gets the value of the р63 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР63() {
        return р63;
    }

    /**
     * Sets the value of the р63 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР63(BigDecimal value) {
        this.р63 = value;
    }

    /**
     * Gets the value of the р64 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР64() {
        return р64;
    }

    /**
     * Sets the value of the р64 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР64(BigDecimal value) {
        this.р64 = value;
    }

    /**
     * Gets the value of the р65 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР65() {
        return р65;
    }

    /**
     * Sets the value of the р65 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР65(String value) {
        this.р65 = value;
    }

    /**
     * Gets the value of the р66 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР66() {
        return р66;
    }

    /**
     * Sets the value of the р66 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР66(String value) {
        this.р66 = value;
    }

    /**
     * Gets the value of the р67 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР67() {
        return р67;
    }

    /**
     * Sets the value of the р67 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР67(BigDecimal value) {
        this.р67 = value;
    }

    /**
     * Gets the value of the р68 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР68() {
        return р68;
    }

    /**
     * Sets the value of the р68 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР68(BigDecimal value) {
        this.р68 = value;
    }

    /**
     * Gets the value of the р69 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getР69() {
        return р69;
    }

    /**
     * Sets the value of the р69 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setР69(BigDecimal value) {
        this.р69 = value;
    }

    /**
     * Gets the value of the р610 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР610() {
        return р610;
    }

    /**
     * Sets the value of the р610 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР610(String value) {
        this.р610 = value;
    }

    /**
     * Gets the value of the р611 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР611() {
        return р611;
    }

    /**
     * Sets the value of the р611 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР611(String value) {
        this.р611 = value;
    }

    /**
     * Gets the value of the р612 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР612() {
        return р612;
    }

    /**
     * Sets the value of the р612 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР612(String value) {
        this.р612 = value;
    }

    /**
     * Gets the value of the р613 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР613() {
        return р613;
    }

    /**
     * Sets the value of the р613 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР613(String value) {
        this.р613 = value;
    }

    /**
     * Gets the value of the р614 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР614() {
        return р614;
    }

    /**
     * Sets the value of the р614 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР614(String value) {
        this.р614 = value;
    }

}
