//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорИстИстДог complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорИстИстДог"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Р9_11" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Иден-лок" /&gt;
 *       &lt;attribute name="Р9_12" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Регн_СВИФТ-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u0418\u0441\u0442\u0418\u0441\u0442\u0414\u043e\u0433")
public class Ф0409303Данные303ДоговорИстИстДог {

    @XmlAttribute(name = "\u04209_11")
    protected String р911;
    @XmlAttribute(name = "\u04209_12")
    protected String р912;

    /**
     * Gets the value of the р911 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР911() {
        return р911;
    }

    /**
     * Sets the value of the р911 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР911(String value) {
        this.р911 = value;
    }

    /**
     * Gets the value of the р912 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР912() {
        return р912;
    }

    /**
     * Sets the value of the р912 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР912(String value) {
        this.р912 = value;
    }

}
