//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:02:12 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303ДоговорТранш complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303ДоговорТранш"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Р2т" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншР2т" minOccurs="0"/&gt;
 *         &lt;element name="Р3т" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншР3т" minOccurs="0"/&gt;
 *         &lt;element name="Р5т" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншР5т" minOccurs="0"/&gt;
 *         &lt;element name="Р6т" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншР6т" minOccurs="0"/&gt;
 *         &lt;element name="Р7т" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншР7т" minOccurs="0"/&gt;
 *         &lt;element name="Р9т" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншР9т" minOccurs="0"/&gt;
 *         &lt;element name="УслТ" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншУслТ" maxOccurs="99" minOccurs="0"/&gt;
 *         &lt;element name="Р4ОбеспТ" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншР4ОбеспТ" maxOccurs="99" minOccurs="0"/&gt;
 *         &lt;element name="НеАТ" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншНеАТ" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="ПогшнТ" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншПогшнТ" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ИстТ" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303ДоговорТраншИстТ" maxOccurs="99" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Р5_2" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}СтрокаДо150Непустая-лок" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u0422\u0440\u0430\u043d\u0448", propOrder = {
    "\u04402\u0422",
    "\u04403\u0422",
    "\u04405\u0422",
    "\u04406\u0422",
    "\u04407\u0422",
    "\u04409\u0422",
    "\u0443\u0441\u043b\u0422",
    "\u04404\u041e\u0431\u0435\u0441\u043f\u0422",
    "\u043d\u0435\u0410\u0422",
    "\u043f\u043e\u0433\u0448\u043d\u0422",
    "\u0438\u0441\u0442\u0422"
})
public class Ф0409303Данные303ДоговорТранш {

    @XmlElement(name = "\u04202\u0442")
    protected Ф0409303Данные303ДоговорТраншР2Т р2Т;
    @XmlElement(name = "\u04203\u0442")
    protected Ф0409303Данные303ДоговорТраншР3Т р3Т;
    @XmlElement(name = "\u04205\u0442")
    protected Ф0409303Данные303ДоговорТраншР5Т р5Т;
    @XmlElement(name = "\u04206\u0442")
    protected Ф0409303Данные303ДоговорТраншР6Т р6Т;
    @XmlElement(name = "\u04207\u0442")
    protected Ф0409303Данные303ДоговорТраншР7Т р7Т;
    @XmlElement(name = "\u04209\u0442")
    protected Ф0409303Данные303ДоговорТраншР9Т р9Т;
    @XmlElement(name = "\u0423\u0441\u043b\u0422")
    protected List<Ф0409303Данные303ДоговорТраншУслТ> услТ;
    @XmlElement(name = "\u04204\u041e\u0431\u0435\u0441\u043f\u0422")
    protected List<Ф0409303Данные303ДоговорТраншР4ОбеспТ> р4ОбеспТ;
    @XmlElement(name = "\u041d\u0435\u0410\u0422")
    protected List<Ф0409303Данные303ДоговорТраншНеАТ> неАТ;
    @XmlElement(name = "\u041f\u043e\u0433\u0448\u043d\u0422")
    protected List<Ф0409303Данные303ДоговорТраншПогшнТ> погшнТ;
    @XmlElement(name = "\u0418\u0441\u0442\u0422")
    protected List<Ф0409303Данные303ДоговорТраншИстТ> истТ;
    @XmlAttribute(name = "\u04205_2", required = true)
    protected String р52;

    /**
     * Gets the value of the р2Т property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорТраншР2Т }
     *     
     */
    public Ф0409303Данные303ДоговорТраншР2Т getР2Т() {
        return р2Т;
    }

    /**
     * Sets the value of the р2Т property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорТраншР2Т }
     *     
     */
    public void setР2Т(Ф0409303Данные303ДоговорТраншР2Т value) {
        this.р2Т = value;
    }

    /**
     * Gets the value of the р3Т property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорТраншР3Т }
     *     
     */
    public Ф0409303Данные303ДоговорТраншР3Т getР3Т() {
        return р3Т;
    }

    /**
     * Sets the value of the р3Т property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорТраншР3Т }
     *     
     */
    public void setР3Т(Ф0409303Данные303ДоговорТраншР3Т value) {
        this.р3Т = value;
    }

    /**
     * Gets the value of the р5Т property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорТраншР5Т }
     *     
     */
    public Ф0409303Данные303ДоговорТраншР5Т getР5Т() {
        return р5Т;
    }

    /**
     * Sets the value of the р5Т property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорТраншР5Т }
     *     
     */
    public void setР5Т(Ф0409303Данные303ДоговорТраншР5Т value) {
        this.р5Т = value;
    }

    /**
     * Gets the value of the р6Т property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорТраншР6Т }
     *     
     */
    public Ф0409303Данные303ДоговорТраншР6Т getР6Т() {
        return р6Т;
    }

    /**
     * Sets the value of the р6Т property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорТраншР6Т }
     *     
     */
    public void setР6Т(Ф0409303Данные303ДоговорТраншР6Т value) {
        this.р6Т = value;
    }

    /**
     * Gets the value of the р7Т property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорТраншР7Т }
     *     
     */
    public Ф0409303Данные303ДоговорТраншР7Т getР7Т() {
        return р7Т;
    }

    /**
     * Sets the value of the р7Т property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорТраншР7Т }
     *     
     */
    public void setР7Т(Ф0409303Данные303ДоговорТраншР7Т value) {
        this.р7Т = value;
    }

    /**
     * Gets the value of the р9Т property.
     * 
     * @return
     *     possible object is
     *     {@link Ф0409303Данные303ДоговорТраншР9Т }
     *     
     */
    public Ф0409303Данные303ДоговорТраншР9Т getР9Т() {
        return р9Т;
    }

    /**
     * Sets the value of the р9Т property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ф0409303Данные303ДоговорТраншР9Т }
     *     
     */
    public void setР9Т(Ф0409303Данные303ДоговорТраншР9Т value) {
        this.р9Т = value;
    }

    /**
     * Gets the value of the услТ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the услТ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getУслТ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорТраншУслТ }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорТраншУслТ> getУслТ() {
        if (услТ == null) {
            услТ = new ArrayList<Ф0409303Данные303ДоговорТраншУслТ>();
        }
        return this.услТ;
    }

    /**
     * Gets the value of the р4ОбеспТ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the р4ОбеспТ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getР4ОбеспТ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорТраншР4ОбеспТ }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорТраншР4ОбеспТ> getР4ОбеспТ() {
        if (р4ОбеспТ == null) {
            р4ОбеспТ = new ArrayList<Ф0409303Данные303ДоговорТраншР4ОбеспТ>();
        }
        return this.р4ОбеспТ;
    }

    /**
     * Gets the value of the неАТ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the неАТ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getНеАТ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорТраншНеАТ }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорТраншНеАТ> getНеАТ() {
        if (неАТ == null) {
            неАТ = new ArrayList<Ф0409303Данные303ДоговорТраншНеАТ>();
        }
        return this.неАТ;
    }

    /**
     * Gets the value of the погшнТ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the погшнТ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getПогшнТ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорТраншПогшнТ }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорТраншПогшнТ> getПогшнТ() {
        if (погшнТ == null) {
            погшнТ = new ArrayList<Ф0409303Данные303ДоговорТраншПогшнТ>();
        }
        return this.погшнТ;
    }

    /**
     * Gets the value of the истТ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the истТ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getИстТ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303ДоговорТраншИстТ }
     * 
     * 
     */
    public List<Ф0409303Данные303ДоговорТраншИстТ> getИстТ() {
        if (истТ == null) {
            истТ = new ArrayList<Ф0409303Данные303ДоговорТраншИстТ>();
        }
        return this.истТ;
    }

    /**
     * Gets the value of the р52 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getР52() {
        return р52;
    }

    /**
     * Sets the value of the р52 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setР52(String value) {
        this.р52 = value;
    }

}
