//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 12:25:39 PM NOVT 
//


package ru.ysolutions.converter.models.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ф0409303Данные303 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ф0409303Данные303"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Договор" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Ф0409303Данные303Договор" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Ид" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}ЦелоеПолож" /&gt;
 *       &lt;attribute name="ОперДень" use="required" type="{urn:cbr-ru:rep0409303:v4.0.4.5}Дата" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u04240409303\u0414\u0430\u043d\u043d\u044b\u0435303", propOrder = {
    "\u0434\u043e\u0433\u043e\u0432\u043e\u0440"
})
public class Ф0409303Данные303 {

    @XmlElement(name = "\u0414\u043e\u0433\u043e\u0432\u043e\u0440", required = true)
    protected List<Ф0409303Данные303Договор> договор;
    @XmlAttribute(name = "\u0418\u0434", required = true)
    protected BigInteger ид;
    @XmlAttribute(name = "\u041e\u043f\u0435\u0440\u0414\u0435\u043d\u044c", required = true)
    protected XMLGregorianCalendar оперДень;

    /**
     * Gets the value of the договор property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the договор property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getДоговор().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ф0409303Данные303Договор }
     * 
     * 
     */
    public List<Ф0409303Данные303Договор> getДоговор() {
        if (договор == null) {
            договор = new ArrayList<Ф0409303Данные303Договор>();
        }
        return this.договор;
    }

    /**
     * Gets the value of the ид property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getИд() {
        return ид;
    }

    /**
     * Sets the value of the ид property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setИд(BigInteger value) {
        this.ид = value;
    }

    /**
     * Gets the value of the оперДень property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getОперДень() {
        return оперДень;
    }

    /**
     * Sets the value of the оперДень property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setОперДень(XMLGregorianCalendar value) {
        this.оперДень = value;
    }

}
